### ISSUE TITLE
[Bug]: issue with wired redstone and its LibNetworkStack packets

### ISSUE THREAD

**Issue by DadoIrie** [someaddons/chunksending#2]
### Describe the bug you're experiencing

![image](https://github.com/someaddons/chunksending/assets/61109153/5f2e1d39-c3f6-4b6c-91a9-d0b5d830d748)
Blocks visibility from [Wired Redstone](https://github.com/Kneelawk/WiredRedstone) are not being sent to the player - regardless if dedicated server or singleplayer
The circuits still work, but they are invisible ... and player only can pass through the wires - whereby the Redstone Diode (`wiredredstone:gate_diode`) - and most likely other non-wires - has a glitchy collision where the screen shakes when player comes in contact with that block - which is invisible because of the missing data 
 
![image](https://github.com/someaddons/chunksending/assets/61109153/65ceaf5c-1d51-444f-963b-cf1d1ec1599d)
enabled mods

### Reproducability

place anything from wired redstone - move a few chunks away - exit world - enter world & go to the spot where the blocks are placed
expected behavior:
![image](https://github.com/someaddons/chunksending/assets/61109153/48a0d829-9c90-4aae-b2d6-cdbbe4f0a1f7)
actual behavior:
server
![image](https://github.com/someaddons/chunksending/assets/61109153/1cbb22d6-1f62-40e6-9035-98ae62757f92)
singleplayer
![image](https://github.com/someaddons/chunksending/assets/61109153/9f265c19-7e63-4629-ae4a-9080da2f6e0b)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://mclo.gs/MQLBfU4 (they don't tell much tho)

**Comment by someaddons** [comment]
Not possible to fix on chunksendings side, chunksending delays the chunk data, which should include all the block of wired redstone, but they apparently are doing a manual custom sync for some reason which when it arrives doesnt have the chunk to add data to yet

**Comment by Kneelawk** [comment]
I don't see any good ways to fix this. The ideal solution would be if FAPI had an event for when a chunk is to be sent to the client. That way you could just invoke that event when a delayed chunk is sent.

One potential solution would be to involve `ThreadedChunkManager.sendChunkDataPackets` when a chunk is actually being sent, as this is where most mods hook in to send custom chunk data. But I can imagine that being difficult.

**Comment by Kneelawk** [comment]
Also just wondering, how does this mod affect the `net.minecraftforge.event.level.ChunkWatchEvent.Watch` event on Forge?

From what I can tell from the javadoc, that event is basically a hook into the method I mentioned before.

**Comment by someaddons** [comment]
it just delays the packet to the client: https://github.com/someaddons/chunksending/blob/1.20.1/src/main/java/com/chunksending/mixin/ChunkHolderMixin.java

**Comment by someaddons** [comment]
you could either change your logic to use the broadcast to send chunk data packets for indirect compat. (Could probably also rework the odd external sync to a normal BE based system/sync). Alternatively you can also add a compatibility patch in your mod yourself and when chunksending is present instead of sendinging it directly you queue it to the player through `IChunksendingPlayer` interface
