### ISSUE TITLE
[Bug]: Any reason why json might not be able to be read on 1.19.2

### ISSUE THREAD

**Issue by lSherozl** [someaddons/chunksending#3]
### Describe the bug you're experiencing

Im getting this error: [25/01/2024 15:47:39 p.m.] [Render thread/ERROR] Could not read config chunksending.json 

### Reproducability

just happens before loading a world

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/lSherozl/1410550c14c4e0881a17182fb7dc2659

**Comment by someaddons** [comment]
Can happen when the config file is broken(wrong braces etc in it) or unaccessable, not a big issue though it just regenerates the config then and recovers
