### ISSUE TITLE
[Bug]: Possible conflict with Emebeddiu m Krypton Reforged/Pluto on 1.19.2 and maybe later versions

### ISSUE THREAD

**Issue by BugmanBugman** [someaddons/chunksending#4]
### Describe the bug you're experiencing

As reported here: https://github.com/embeddedt/embeddium/issues/144 and https://github.com/embeddedt/embeddium/wiki/Unsupported-mods#chunk-sending-when-installed-with-kryptonpluto
Using these mods together seems to mess up rendering of certain blocks.
Here is a video:https://imgur.com/SJDBu0I
User's mod lists
"Embeddium
Chunk Sending mod, [here is the Curseforge link](https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric) to its description, it changes the chunk packet sending logic
Cupboard Utilities, a dependency
Pluto or Krypton Reforged
Starlight
Workshop for handsome adventurers - the mod the rendering issue occurs with
Simple Drying Racks - another mod where this rendering issue occurs"

### Reproducability

"Create a world, place down a tool rack from the Workshop mod and/or a drying rack from Simple Drying Racks
Insert a supported tool or food item
Save the world and fully exit the game
Start the game, load the world
Attempt to interact with the racks by either taking or inserting the items
The tool rack won't be properly updated
Place a block nearby, presentation is updated
The issue will no longer occur (at least with this specific tool rack) until the game instance is fully restarted"

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

None required

**Comment by someaddons** [comment]
logs are requied, please add them

**Comment by someaddons** [comment]
Closing since chunksending is a serverside mod, which cannot have any impact on rendering. Most likely embeddiums chunk tracking system is buggy, though that is on the performance mod to fix

**Comment by border999** [comment]
https://github.com/FiniteReality/embeddium/wiki/Unsupported-mods
If both Chunk Sending and a Krypton port are installed, their optimizations conflict, causing strange behavior such as blocks not updating correctly when interacting with chunks. Remove one of the mods.
