### ISSUE TITLE
Can this be used on 1.21?

### ISSUE THREAD

**Issue by Legendmanj** [someaddons/chunksending#5]
1.21 is the latest minecraft version currently, and I would like to know whether this mod can be used on 1.21 server-side without issues?

Seems the mod is still on 1.20.1 with no updates noticed
would really appreciate it if it is done soon or to notify me asap if it can be used on 1.21 servers without issues! (;

**Comment by someaddons** [comment]
@Legendmanj released 1.21^^

**Comment by VaporeonScripts** [comment]
would this mod benefit single player worlds and/or lan open world with e4mc?
