### ISSUE TITLE
[Bug]: Incompatibility with Minecraft Transit Railway Mod 

### ISSUE THREAD

**Issue by WalterLezerus** [someaddons/chunksending#6]
### Describe the bug you're experiencing

I join a world, add stuff from the MTR mod, rejoin world and all the rails and other stuff that should have saved isn't there anymore. I disable your mod and retry this and the objects remain.

### Reproducability

Install both the MTR mod, the one i used was version 3.2.2 Hotfix 2, and the latest version of your mod for 1.20.1.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/WalterLezerus/8627e52a955656c48f6a95e8a1a9bba3

**Comment by someaddons** [comment]
do you maybe mean a different mod than chunksending? Chunksending only alters the rate at which data is sent to the client, it has no relation to data saving

**Comment by WalterLezerus** [comment]
No, it was definitely your mod that had issues. We tested disabling different mods and loading the rejoining a world but once we disabled your mod and only your mod did it actually save the data from the train mod.

**Comment by someaddons** [comment]
![image](https://github.com/user-attachments/assets/959789bc-37b1-4f86-94af-6bd90399dbfd)
works just fine for me, are you sure you mean the "chunksending" mod? if so it might be a correlation <-> causation switchup

**Comment by WalterLezerus** [comment]
I do mean the chunksending mod. While it was disabled, I was able to save the world properly. I rejoined to make sure it had the stuff still there. Then I left, closed minecraft enabled your mod and rejoined left and joined again and it was all gone. it allowed me to place stuff while the world was up but once it restarted it all vanished.

**Comment by someaddons** [comment]
well I cannot reproduce it at all, and chunksending isnt related to saving of chunks either so most likely some other mod is causing this, maybe in combination with chunksending being isntalled.
