### ISSUE TITLE
[Bug]: incompatibility with more culling

### ISSUE THREAD

**Issue by VaporeonScripts** [someaddons/chunksending#7]
### Describe the bug you're experiencing

https://mclo.gs/5GFo5T1

### Reproducability

put this mod and more culling (1.21.1 neoforge .61)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21.1

### Modloader version

Forge

### Logs

https://mclo.gs/5GFo5T1

**Comment by VaporeonScripts** [comment]
also, does the mod work in singleplayer,and would it work with lan hosted world using e4mc mod? (just to know if i  have an useless mod xD)

**Comment by someaddons** [comment]
ye it does work in singeplayer/lan too, this issue though doesnt have anything to do with chunksending, probably just the coremodding of mixinsquared/moreculling failing
